version: '3'
services:
  flask_app:
    image: dock_deploy:latest
    container_name: flask_app
    ports:
      - "5000:5000"
    networks:
      - monitoring
    restart: always

  prometheus:
    image: prom/prometheus:v2.42.0
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - monitoring
    restart: always

  grafana:
    image: grafana/grafana:8.5.3
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - monitoring
    restart: always

networks:
  monitoring:
    driver: bridge
